- VIA/VIA.download.recipe
Hey @macmule, 
Here's the PR for issue #22.
> VIA Url Updates

- Unity3D/UnityHub.pkg.recipe
I also making a pull request to update the parent recipe name to com.github.hansen-m.download.UnityHub
> Changes to clarify between Unity Hub and Editor

- MediaHuman YouTube Downloader-Trial/MediaHuman YouTube Downloader-Trial.download.recipe
- Webrecorder Player/Webrecorder Player.download.recipe
Context: The [CodeSignatureVerifier](https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification) processor ensures that the downloaded applications/packages are signed by the expected developer certificate. Although this is not a guarantee that the payload is trouble-free, it's a good indicator that the file you downloaded is the one you intended to download.
> Add CodeSignatureVerifier processor

- Gladinet Cloud Mac Client 9/Gladinet Cloud Mac Client 9.download.recipe
- SteelSeries/SteelSeriesEngine.download.recipe
I tested the modified recipes with `autopkg run --check` but you may want to do the same just to be sure.
> Update to HTTPS

- Desktoppr/Desktoppr.munki.recipe
We'd like to not go to production immediately :)
> Change default catalog

- BoxDrive/BoxDrive-ExtensionAttribute.xml
> Fix extension attribute shebang #93

- Platypus/Platypus.pkg.recipe
Got this error:
```
Processor: Copier: Error: Error processing path '/Users/admin/Library/AutoPkg/Cache/com.github.dataJAR-recipes.pkg.Platypus/Platypus/Platypus-5.3/Platypus.app' with glob.
```
> Change processor to AppPkgCreator

- Microsoft Excel 2019/Microsoft Excel 2019.munki.recipe
- Microsoft Excel 365/Microsoft Excel 365.munki.recipe
- Microsoft OneNote 365/Microsoft OneNote 365.munki.recipe
- Microsoft Outlook 2019/Microsoft Outlook 2019.munki.recipe
- Microsoft Outlook 365/Microsoft Outlook 365.munki.recipe
- Microsoft PowerPoint 2019/Microsoft PowerPoint 2019.munki.recipe
- Microsoft PowerPoint 365/Microsoft PowerPoint 365.munki.recipe
- Microsoft Word 2019/Microsoft Word 2019.munki.recipe
- Microsoft Word 365/Microsoft Word 365.munki.recipe
Minimum OS version is now 10.14 for the core suite.
> Bump Microsoft Office Minimum OS Requirements

- Jamf Connect 2/Jamf Connect 2.munki.recipe
- Jamf Connect 2/Jamf Connect 2.pkg.recipe
Recipe output:
```
autopkg run -vv ~/Documents/git/dataJAR-recipes-1/Jamf\ Connect\ 2/Jamf\ Connect\ 2.munki.recipe 
Processing /Users/autopkgadmin/Documents/git/dataJAR-recipes-1/Jamf Connect 2/Jamf Connect 2.munki.recipe...
WARNING: /Users/autopkgadmin/Documents/git/dataJAR-recipes-1/Jamf Connect 2/Jamf Connect 2.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'JamfConnect.dmg',
'url': 'https://files.jamfconnect.com/JamfConnect.dmg'}}
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing …
```
> JamfConnect2 updates - use PlistReader

- Shared Processors/DistributionPkgInfo.py
The DistributionPkgInfo shared processor had two issues fixed by this PR:
- Upon running, it would create a folder at the literal path `'file_path'` instead of at the path specified by the `file_path` variable. This left an empty folder at the current working directory used for running AutoPkg.  The path has been changed from a string back to a variable.
- `OSError` is probably not the right exception to catch here. When I try to create a folder at a path that I don't own, I get `PermissionError`. Regardless, I think any exception is worth raising, which removal of the `try` block allows.
Here's the verbose run output for a recipe that references the updated DistributionPkgInfo processor:
```
% autopkg run -vv BoxDrive.munki MakeCatalogs.munki        
Processing BoxDrive.munki...
WARNING: …
```
> Adjust mkdir operation in DistributionPkgInfo shared processor

- macOSLAPS/macOSLAPS.munki.recipe
> One more description fix

- Andrew Belt/VCV Rack.munki.recipe
I *think* this is the last "Labels and Addresses" encroachment... :)
_Edit: Nope, [one more](https://github.com/autopkg/dataJAR-recipes/pull/158) to follow!_
> Fix description

- VMware Fusion 12/VMware Fusion 12.jss.recipe
Fixed the Self Service Icon value.
> Fixed the Self Service Icon value

- BrowserStackLocal/BrowserStackLocal App.munki.recipe
> Wrong displayname was provided here

- OpenVPN Connect Client/OpenVPN Connect Client 3.download.recipe
- OpenVPN Connect Client/OpenVPN Connect Client 3.munki.recipe
With apologies for the tabbing, but the tabbing of the original files is a bit of a mess and I tried not to correct it unnecessarily :)
> Fixes to support new dmg from OpenVPN with separate architecture pkgs

- Connect Fonts/Connect Fonts.download.recipe
Increment Sparkle URL to current version
> Update Connect Fonts.download.recipe

- VMware Fusion 13/VMware Fusion 13.munki.recipe
> Update display name for VMware Fusion 13

- Noun Project/Noun Project.pkg.recipe
Last commit: 
https://github.com/autopkg/dataJAR-recipes/commit/af9b754111129b8a0e6590fdce4a1edf625ed465
Related issue: #282 282
> Required changes due to last commit to download recipe

- Godot 4/Godot 4.pkg.recipe
Created a pkg recipe for Godot 4
> Create Godot 4.pkg.recipe

- Jamf Connect 2/Jamf Connect 2.munki.recipe
Changed pkg_payload in PkgPayloadUnpacker to reflect new expanded pkg name of JamfConnectMenubar.pkg.
> Update Jamf Connect 2.munki.recipe

- Jamf Connect 2/Jamf Connect 2.pkg.recipe
Fix for #290 
Same as recent munki recipe change
> Update Jamf Connect 2.pkg.recipe

- Max 8/Max 8.download.recipe
Changed search pattern to accommodate new Cycling74 CDN URL.
> Update Max 8.download.recipe

- Postman/Postman.download.recipe
- Postman/Postman.munki.recipe
This adds Munki's `supported_architectures` key.
> Postman updates

- Screen Pal 3/Screen Pal 3.download.recipe
The download has changed from a .dmg to a .pkg.
> Update Screen Pal 3 for new distribution format

- VIA/VIA.download.recipe
```
autopkg run via.download.recipe -v       
Processing via.download.recipe...
URLTextSearcher: Found matching text (match): https://cdn.kramerav.com/web/downloads/setups/via_mac_dmg_v4.0.3.1350.zip
URLDownloader
URLDownloader: Storing new Last-Modified header: Thu, 28 Sep 2023 08:44:51 GMT
URLDownloader: Storing new ETag header: 0x8DBBFFF2E2A4B76
URLDownloader: Downloaded /Users/Shared/AutoPkg/Cache/local.download.VIA/downloads/via_mac_dmg_v4.0.3.1350.zip
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename via_mac_dmg_v4.0.3.1350.zip
Unarchiver: Unarchived /Users/Shared/AutoPkg/Cache/local.download.VIA/downloads/via_mac_dmg_v4.0.3.1350.zip to /Users/Shared/AutoPkg/Cache/local.download.VIA/unzip/
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: …
```
> VIA URL & VersionSplitter Update

- Krisp/Krisp.download.recipe
https://macadmins.slack.com/archives/C056155B4/p1680029995483949
> Update Krisp download URL

- Krita/Krita.download.recipe
> Updated regex for Krita download URL

- .pre-commit-config.yaml
- Max 9/Max 9.download.recipe
- Max 9/Max 9.munki.recipe
Search pattern changed to reflect release of Max 9.0.0.
> Initial Commit of Max 9

- Adobe Admin Console Packages/AdobeAdminConsolePackagesImporter.py
> Bug fix for multiple override dirs

- Spyder/Spyder.download.recipe
- Spyder/Spyder.munki.recipe
Hello,
I updated the Spyder-IDE recipes to be able to select for which architecture one wants to download.
I also added code signature verification to the download recipe.
Regards,
Julian
> Update Spyder Recipes

- Adobe Admin Console Packages/AdobeAdminConsolePackagesImporter.py
Addresses:
- #380
- #381
- #384
> Adobe admin console packages importer 3.1.4

- SageMath/SageMath.download.recipe
This PR sets a default architecture to download for SageMath recipes. Intel has been chosen because of the relative ubiquity of Rosetta2 installs — this could be switched to Apple Silicon in future years.
Having a default architecture specified does not affect usage of users who have already created overrides, but ensure the recipe is runnable by default and therefore easier to test and maintain.
```
% autopkg run -vvq '~/Developer/repo-lasso/repos/autopkg/dataJAR-recipes/SageMath/SageMath.download.recipe'
Processing ~/Developer/repo-lasso/repos/autopkg/dataJAR-recipes/SageMath/SageMath.download.recipe...
WARNING: ~/Developer/repo-lasso/repos/autopkg/dataJAR-recipes/SageMath/SageMath.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is …
```
> Add default architecture for SageMath download

- TouchDesigner/TouchDesigner.download.recipe
- TouchDesigner/TouchDesigner.munki.recipe
This PR changes the TouchDesigner.munki parent recipe to the download recipe in moofit-recipes, and deprecates the download recipe in this repo.
```
% autopkg run -vvq TouchDesigner.munki.recipe
Processing TouchDesigner.munki.recipe...
WARNING: TouchDesigner.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'Input': {'re_pattern': 'https://download.derivative.ca/TouchDesigner.[0-9]+.[a-zA-Z0-9]+.intel.dmg',
'request_headers': {'user-agent': 'Mozilla/5.0 (Macintosh; Intel '
'Mac OS X 10_15_7) '
'AppleWebKit/605.1.15 (KHTML, '
'like Gecko) Version/16.0 '
'Safari/605.1.15'},
'result_output_var_name': 'DOWNLOAD_URL',
'url': 'https://derivative.ca/download/release-download/39'}}
URLTextSearcher: Found …
```
> Change parent of TouchDesigner munki recipe, deprecate download recipe

- Anki/Anki.download.recipe
- Anki/Anki.munki.recipe
This PR switches the parent recipe of Anki.munki to the hansen-m download recipe, and deprecates the download recipe in this repo.
Verboose recipe run output:
```
% autopkg run -vvq Anki.munki.recipe
Processing Anki.munki.recipe...
WARNING: Anki.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': '.*apple.*', 'github_repo': 'ankitects/anki'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting default value of: ~/.autopkg_gh_token
GitHubReleasesInfoProvider: …
```
> Change parent recipe of Anki.munki

- LogiTune/LogiTune.download.recipe
- LogiTune/LogiTune.pkg.recipe
This PR changes the LogiTune.pkg parent recipe to the download recipe in ahousseini-recipes, and deprecates the download recipe in this repo.
```
% autopkg run -vvq LogiTune.{munki,pkg}.recipe
Processing LogiTune.munki.recipe...
WARNING: LogiTune.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'LogiTune.dmg',
'url': 'https://software.vc.logitech.com/downloads/tune/LogiTuneInstaller.dmg'}}
URLDownloader: Storing new Last-Modified header: Sat, 07 Dec 2024 00:11:13 GMT
URLDownloader: Storing new ETag …
```
> Change parent of LogiTune pkg recipes, deprecate download recipe

- Vanta Agent/Vanta Agent.download.recipe
- Vanta Agent/Vanta Agent.munki.recipe
This PR changes the Vanta Agent.munki parent recipe to the download recipe in nstrauss-recipes, and deprecates the download recipe in this repo.
```
% autopkg run -vvq Vanta\ Agent.munki.recipe
Processing Vanta Agent.munki.recipe...
WARNING: Vanta Agent.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'VantaAgent.pkg',
'url': 'https://vanta-agent-repo.s3.amazonaws.com/targets/versions/latest/vanta-universal.pkg'}}
URLDownloader: Storing new Last-Modified header: Thu, 02 Jan 2025 00:32:02 GMT …
```
> Change parent of Vanta Agent munki recipe, deprecate download recipe

- NVivo 15/NVivo 15.download.recipe
https://download.qsrinternational.com/Software/NVivo15forMac/NVivo.dmg downloads 15.0
https://download.qsrinternational.com/Software/NVivo15forMac/NVivo15.dmg downloads 15.1
> Updated NVivo 15 URL

- Ultimaker Cura/Ultimaker Cura.download.recipe
Fixed requirement in CodeSignatureVerifier (to what they should have been using all along)
> Update Ultimaker Cura.download.recipe

- DotNet 8 SDK/DotNet 8 SDK.download.recipe
- DotNet 9 SDK/DotNet 9 SDK.download.recipe
Looks like Microsoft has changed the domain from which they're hosting DotNet downloads. 
Successful v8 run:
```
autopkg run -vvvv /Users/tyler.sparr/Downloads/dataJAR-recipes/DotNet\ 8\ SDK/DotNet\ 8\ SDK.download.recipe
Processing /Users/tyler.sparr/Downloads/dataJAR-recipes/DotNet 8 SDK/DotNet 8 SDK.download.recipe...
WARNING: /Users/tyler.sparr/Downloads/dataJAR-recipes/DotNet 8 SDK/DotNet 8 SDK.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'ARCH_TYPE': 'x64',
'AUTOPKG_VERSION': '2.7.3',
'MUNKI_REPO': '/Volumes/MUNKI',
'NAME': 'DotNet8SDK',
'PARENT_RECIPES': [],
'RECIPE_CACHE_DIR': '/Users/tyler.sparr/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.DotNet '
'8 SDK',
'RECIPE_DIR': …
```
> Updated DotNet Download URL Domain

- Omnissa Horizon Client/Omnissa Horizon Client.download.recipe
Developer ID updated to Wandering WiFi LLC
> Update Omnissa Horizon Client.download.recipe
