autopkg/dataJAR-recipes

Blue Jeans Scheduler for Mac/Blue Jeans Scheduler for Mac.munki.recipe
The description for the Blue Jeans Scheduler was incorrect and was _actually_ the description for iOS Console. Corrected it with some html to look nice.
=> Update Blue Jeans Scheduler description

JumpCloud Agent/JumpCloud Agent.munki.recipe
Fix for issue #8 where the Munki client will re-install an older
version of the JumpCloud agent after the agent auto-updates. Removes
generation of an installs array so that the Munki client uses receipts
to determine if an update should occur.
=> Remove installs array from JumpCloud Agent.munki

UNetbootin/UNetbootin.munki.recipe
I was able to uninstall unetbootin while the application was still running in memory.
=> Add blocking_applications

OpenJDK12/OpenJDK12.munki.recipe
The underlying URL changed in the SEARCH_PATTERN which causes the recipe to fail. This was fixed in this commit to the .download recipe here (https://github.com/autopkg/rtrouton-recipes/commit/aea03dad000b90f8da073ce16983f4f1d681ad24), however, since it is defined in this recipe, it overrides the fix.
=> Remove redundant SEARCH_URL and SEARCH_PATTERN

Abstract/Abstract.pkg.recipe, DB Browser for SQLite/DB Browser for SQLite.pkg.recipe, Figma/Figma.download.recipe, Genymotion/Genymotion.pkg.recipe, KeeWeb/KeeWeb.pkg.recipe, KeyStore Explorer/KeyStore Explorer.pkg.recipe, LXFree/LXFree.pkg.recipe, MPEG Streamclip/MPEG Streamclip.pkg.recipe, PPPC-Utility/PPPC-Utility.download.recipe, Platypus/Platypus.pkg.recipe, Scratch Desktop/Scratch Desktop.pkg.recipe, The MUT/The MUT.pkg.recipe, UNetbootin/UNetbootin.pkg.recipe
Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.
=> Remove NAME variable from app paths

.pre-commit-config.yaml, CrashPlan for Enterprise 6/CrashPlan for Enterprise 6.jss.recipe, Cubase 9/Cubase 9.jss.recipe, Cubase 9/Cubase 9.munki.recipe, Cubase LE AI Elements 9/Cubase LE AI Elements 9.jss.recipe, Cubase LE AI Elements 9/Cubase LE AI Elements 9.munki.recipe, Desktoppr/Desktoppr.munki.recipe, MacTeX Ghostscript/MacTeX Ghostscript.jss.recipe, SketchUp Viewer EN/SketchUp Viewer EN.download.recipe, SketchUp Viewer EN/SketchUp Viewer EN.munki.recipe, Swiss-PdbViewer/Swiss-PdbViewer.jss.recipe, VMware Fusion 10/VMware Fusion 10.jss.recipe, VMware Fusion 11/VMware Fusion 11.jss.recipe, VMware Fusion 8/VMware Fusion 8.jss.recipe, WaveLab Elements 9.5/WaveLab Elements 9.5.jss.recipe, WaveLab Elements 9.5/WaveLab Elements 9.5.munki.recipe, WaveLab LE 9.5/WaveLab LE 9.5.jss.recipe, WaveLab LE 9.5/WaveLab LE 9.5.munki.recipe, WaveLab LE 9/WaveLab LE 9.jss.recipe, WaveLab LE 9/WaveLab LE 9.munki.recipe
Pre-commit should effectively prevent the resolved issues from happening again in the future. To configure, each contributor should [install pre-commit](https://pre-commit.com/#install), change to the repo directory, and run `pre-commit install` to activate the hooks.
Related quick talk from MacDevOpsYVR:
https://www.youtube.com/watch?v=1UCyGC6DVOU
=> Fix plist parsing errors, remove trust info, and add pre-commit config

Ultimaker Cura/UltimakerCura-CFBundleVersionExtensionAttribute.xml
This was causing the EA to fail when ran on clients during an inventory.
=> Fixed the specified interpreter in the shebang

US-20x20_SettingsPanel/US-20x20_SettingsPanel.download.recipe, US-20x20_SettingsPanel/US-20x20_SettingsPanel.munki.recipe, US-20x20_SettingsPanel/US-20x20_SettingsPanel.pkg.recipe
Child recipes and overrides will break upon merging this, but it looks like there aren't any child recipes in the autopkg org. You'll have to fix your local overrides manually.
=> Align US-20x20 Settings Panel identifiers with standard

.pre-commit-config.yaml, Abstract/Abstract.download.recipe, KeePassXC/KeePassXC.verify.recipe, Luxafor/Luxafor.download.recipe
Other changes detailed here: https://github.com/homebysix/pre-commit-macadmin/compare/v1.4.0...v1.5.1
=> Update to pre-commit hooks version 1.5.1, which includes EndOfCheckPhase verification

4K Video Downloader/4K Video Downloader.download.recipe, 4K Video Downloader/4K Video Downloader.munki.recipe
Without this change, I was getting duplicate imports because the developer was re-using CFBundleShortVersionStrings. Looks like CFBundleVersion prevents that issue.
```
The following new items were imported into Munki:
Name               Version  Catalogs  Pkginfo Path                        Pkg Repo Path                     
----               -------  --------  ------------                        -------------                     
4KVideoDownloader  4.9.2    testing   apps/4KVideoDownloader-4.9.2.plist  apps/4KVideoDownloader-4.9.2.dmg  
```
=> Version 4K Video Downloader using CFBundleVersion key

VIA/VIA.download.recipe, VIA/VIA.pkg.recipe
This allows the URL to change within overrides, if a new version of VIA is released, and the URL in the recipe needs to change.
Merry Christmas!
=> Added URL to input, as URL was set to an older version.

The MUT/The MUT.download.recipe
Current recipe run finds no match on the https://jssmut.weebly.com site
- Use `GitHubReleasesInfoProvider` instead
- Add PRERELEASE input variable
- Update description to indicate Github download
- Simplify `input_path` variable in CodeSignature processor since URLDownloader processor uses `pathname` variable for downloaded file path.
=> Fix & update MUT download recipe

Cisco Webex Meetings/Cisco Webex Meetings.download.recipe
It looks like they changed the filename from webex.pkg to Cisco Webex Meetings Cloud.pkg. After this minor change everything went as expected.
=> New package name after FlatPkgUnpacker process

Adobe 2020/README.md
- Fix some minor typos & grammar
- Indent example Adobe package titles
- Add & update steps 2-6.  Details about managed install per #39, add Adobe downloader steps.  Also make explicit the fact that the `NAME` input variable must match the Adobe package title.
- Add assumed override path
=> Update Adobe 2020 README.md

VMware Fusion 11/VMware Fusion 11.download.recipe
Changed out the `Copier` processor for the `FileMover` processor to fix a problem with code signatures being broken:
Links: 
[https://github.com/autopkg/dataJAR-recipes/issues/89](https://github.com/autopkg/dataJAR-recipes/issues/89)
[https://kb.vmware.com/s/article/2058680](https://kb.vmware.com/s/article/2058680)
=> Update VMware Fusion 11.download.recipe

VMware Fusion 11/VMware Fusion 11.pkg.recipe
When Neil applied my previous (version-agnostic) merge, but switched to a different v11 URL handler [removing all acknowledgement of my contributions in the process ;) ] he forgot to revert my NAME change.  Doing that now.
=> Fix name change incorrectly applied from merge

KeyStore Explorer/KeyStore Explorer.pkg.recipe
I get this error:
```
The following recipes failed:
KeyStore Explorer.pkg
Error in com.github.dataJAR-recipes.pkg.KeyStore Explorer: Processor: Copier: Error: Error processing path '/private/tmp/dmg.MXfjFo/KeyStore Explorer 5.4.3.app' with glob. 
```
=> Switch to AppPkgCreator processor

QLab4/QLab4.download.recipe
Also lint the recipe for consistent formatting (there had been a mix of spaces and tabs for indents; all dict keys now alphabetical). Feel free to reject if you don't like the linting.
=> Hardcode Sparkle Feed for QLab4.download

Miro/Miro.download.recipe, Miro/Miro.munki.recipe
The current Miro download URL only pulls the old version - v0.3.33. This PR changes it to the new URL using miro.com instead of realtimeboard.com. With the two minor URL changes I was able to pull the latest version of Miro - v0.4.2.
Please let me know if anything else is needed to complete this PR.
-bryan
=> Updated Miro download URL

Figma/Figma.jss.recipe
This key caused the following error:
`Error: JSSImporter can't find a package at '%target%'`
Removing the unnecessary key solved the issue and the recipe works as intended. Let me know if you have any feedback. Thanks for all your work!
=> Figma.jss.recipe: Removed pkg_path key

Code42/Code42.download.recipe, Code42/Code42.munki.recipe
Recipe output:
```
autopkg run -vv ~/Documents/git/dataJAR-recipes-1/Code42/Code42.munki.recipe      11s 20:37:30
Processing /Users/autopkgadmin/Documents/git/dataJAR-recipes-1/Code42/Code42.munki.recipe...
WARNING: /Users/autopkgadmin/Documents/git/dataJAR-recipes-1/Code42/Code42.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'Code42.dmg',
'url': 'https://download.code42.com/installs/agent/latest-mac.dmg'}}
URLDownloader: Storing new Last-Modified header: Mon, 19 Oct 2020 18:13:18 GMT
URLDownloader: Storing new ETag header: …
```
=> Code42 updates

Polycom Content App/PolycomContentApp.munki.recipe
This recipe intends to import the PolycomContent software into the **apps/polycom** subdirectory, but because the `MUNKI_REPO_SUBDIR` key is set in the `pkginfo` dict and not the `Input` dict, the substitution never occurs. The actual subdirectory created is called literally `%MUNKI_REPO_SUBDIR%`.
This PR brings the `MUNKI_REPO_SUBDIR` key back out into the `Input` dict where it belongs, ensuring that the substitution occurs properly.
Here's the recipe run output before the change (note incorrect import path):
```
% autopkg run -vv PolycomContentApp.munki MakeCatalogs.munki
Processing PolycomContentApp.munki...
WARNING: PolycomContentApp.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'Input': {'re_pattern': …
```
=> Adjust incorrect Munki repo subdirectory in PolycomContent recipe

MediaHuman YouTube Downloader-Trial/MediaHuman YouTube Downloader-Trial.download.recipe, Rectangle/Rectangle.download.recipe, Webrecorder Player/Webrecorder Player.download.recipe
The correct argument name for [CodeSignatureVerifier](https://github.com/autopkg/autopkg/wiki/Processor-CodeSignatureVerifier) is `requirement`.
=> Adjust name of CodeSignatureVerifier argument

.pre-commit-config.yaml, Blue Jeans Events/Blue Jeans Events.download.recipe, CLO/CLO.download.recipe, CrashPlan/CrashPlan.download.recipe, CrashPlanPROe/CrashPlanPROeClient.munki.recipe, Framer Desktop-Trial/Framer Desktop-Trial.download.recipe, Framer X-Trial/Framer X-Trial.download.recipe, Jamf Connect Login/Jamf Connect Login Okta.munki.recipe, Jamf Connect Login/Jamf Connect Login.munki.recipe, Jamf Connect Sync/Jamf Connect Sync.munki.recipe, Jamf Connect Verify/Jamf Connect Verify.munki.recipe, KeyStore Explorer/KeyStore Explorer.pkg.recipe, Microsoft Azure Storage Explorer/Microsoft Azure Storage Explorer.download.recipe, NVivo 12/NVivo 12.download.recipe, PRTG Desktop/PRTG Desktop.download.recipe, Platypus/Platypus.pkg.recipe, Razer Synapse 2/Razer Synapse 2.download.recipe, Red Giant Trapcode Suite/Red Giant Trapcode Suite.download.recipe, SMART Education Software Web/SMART Education Software Web.download.recipe, Stretchly/Stretchly.download.recipe, eLicenser Control/eLicenser Control.download.recipe
Includes:
- MinimumVersion adjustments based on processors used
- Adding or adjusting placement of EndOfCheckPhase processor in download recipes
- Avoiding using `%NAME%` in places where overriding the name could break recipe function (e.g. CodeSignatureVerifier)
After these changes, `pre-commit` passes all checks:
```
% pre-commit run --all-files
Check AutoPkg Recipes....................................................Passed
Forbid AutoPkg Overrides.................................................Passed
Forbid AutoPkg Trust Info................................................Passed
```
Reminder: have the people contributing to the recipe repo install pre-commit (`brew install pre-commit`) and activate its hooks in the repo (`pre-commit install`) in order to catch these things before …
=> Various fixes surfaced by `pre-commit run --all-files`

Catalyst Browse/Catalyst Browse.download.recipe, Catalyst Prepare/Catalyst Prepare.download.recipe, Foldr/Foldr.download.recipe, Hype 3-Trial/Hype 3-Trial.download.recipe, Hype 4-Trial/Hype 4-Trial.download.recipe, Jump Desktop Connect/Jump Desktop Connect.download.recipe
The `filename` argument should be in URLDownloader, not SparkleUpdateInfoProvider. Adjusted arguments and added version to filename.
=> Adjust SparkleUpdateInfoProvider and URLDownloader arguments

Apple Mastering Tools/Apple Mastering Tools.munki.recipe, Citrix Files for Mac/Citrix Files for Mac.munki.recipe, CrashPlan for Enterprise 6/CrashPlan for Enterprise 6.munki.recipe, Cubase 9.5/Cubase 9.5.munki.recipe, Cubase 9/Cubase 9.munki.recipe, Cubase LE AI Elements 9.5/Cubase LE AI Elements 9.5.munki.recipe, Cubase LE AI Elements 9/Cubase LE AI Elements 9.munki.recipe, Gladinet Cloud Mac Client 9/Gladinet Cloud Mac Client 9.munki.recipe, Malwarebytes 3/Malwarebytes 3.munki.recipe, Resolume Arena/Resolume Arena.munki.recipe, Resolume Avenue/Resolume Avenue.munki.recipe, Swiss-PdbViewer/Swiss-PdbViewer.munki.recipe, SwitchResX4-Trial/SwitchResX4-Trial.munki.recipe, WaveLab Elements 9.5/WaveLab Elements 9.5.munki.recipe, WaveLab LE 9.5/WaveLab LE 9.5.munki.recipe, WaveLab LE 9/WaveLab LE 9.munki.recipe
`additional_pkginfo` belongs in the [MunkiPkginfoMerger](https://github.com/autopkg/autopkg/wiki/Processor-MunkiPkginfoMerger) processor.
=> Adjust MunkiPkginfoMerger arguments

AWSCLI/AWSCLI.jss.recipe
The parent recipe has been copied to homebysix-recipes in order to prepare for cgerke-recipes deprecation. For details, see: autopkg/cgerke-recipes#37
=> Change parent recipe for cgerke-recipes deprecation

CrashPlan for Enterprise 6/CrashPlan for Enterprise 6.pkg.recipe
This PR fixes two variable values in the FlatPkgUnpacker and the PkgRootCreator which previously would have caused the recipe to fail.
The recipes in this PR have been tested now and are functional again.
=> Fix FlatPkgUnpacker flat_pkg_path value

Figma/Figma.download.recipe
I ran this recipe today and found that the identifier has changed ever so slightly - looks like they changed it to reflect that they're building universal:
❯ codesign --display -r- ~/Downloads/Figma.app
Executable=/Users/rick.heil/Downloads/Figma.app/Contents/MacOS/DynamicUniversalApp
designated => identifier "com.figma.desktop.dynamic-universal-app" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = T8RA8NE3B7
This PR updates the requirement to match what is being shipped.
=> Update code signature requirement for Figma

Figma/Figma.download.recipe
Figma seems to have rolled back their code signature identifier to "com.figma.Desktop" from "com.figma.desktop.dynamic-universal-app" or changed the application upstream at the download URL back to the Intel only variant.
=> Code signature identifier reverted

Adobe 2021/Adobe2021Versioner.py
Looks like at least Animate 2021 requires this change now
=> Animate 2021 Fallback to JSON Versioning

Microsoft Excel 365/Microsoft Excel 365.munki.recipe, Microsoft OneNote 365/Microsoft OneNote 365.munki.recipe, Microsoft Outlook 365/Microsoft Outlook 365.munki.recipe, Microsoft PowerPoint 365/Microsoft PowerPoint 365.munki.recipe, Microsoft Word 365/Microsoft Word 365.munki.recipe
According to [MS](https://support.microsoft.com/en-us/office/upgrade-macos-to-continue-receiving-microsoft-365-and-office-for-mac-updates-16b8414f-08ec-4b24-8c91-10a918f649f8), macOS 10.15 is needed from Dec 2021 on. However, we experienced issues with 10.14 clients not being able to start the Office apps updated to version 16.55.
=> Set minimum_os_version to 10.15.0

Krisp/Krisp.munki.recipe
The newest version of Krisp allows you to set a trigger file to have have it skip launching on post install
=> added preinstall script

Anaconda 3/Anaconda3.munki.recipe
Same as the Anaconda.download recipe, just without the deprecation warning!
=> Switch to Anaconda3.download recipe

BoxDrive/BoxDrive.munki.recipe
Box Drive's process name is just "Box". If this isn't added, Box Drive will yell at the user when you try to upgrade it.
=> Adding blocking applications

Code42/Code42-arm64.download.recipe, Code42/Code42-arm64.munki.recipe
This is one of 2 PR options I'm offering to add the ability for admins to download the newly released arm64-specific version of Code42 which was introduced with version 8.8.2.
This option simply duplicates the recipes to hardcode the new arm64-specific download URL, updates the descriptions, and adds a `supported_architectures` section to the munki recipe.
=> Add arm64 Code42 support: Option #1

Figma/Figma.download.recipe
Allow the installation of device native versions of Figma via input variable. 
Expanded the description accordingly
=> Add multiarch-support for Figma through input variable

Ultimaker Cura/Ultimaker Cura.pkg.recipe
Using `CFBundleShortVersionString` as `CFBundleVersion` is no longer present in the apps' Info.plist.
=> Ultimaker Cura: Updating the plist key that contains the version

Microsoft Word 2019/Microsoft Word 2019.munki.recipe
The reason we need to do that on our end is because sometimes different packages install different versions of Microsoft Auto Update and then start reinstalling over and over again. 
The used processor is gonna be part of one of the next updates on AutoPKG to make it a core processor and the dependency to a custom processor can be relieved soonish.
=> Add optional flag to MAU pkg receipt

Axure RP 10-Trial/Axure RP 10-Trial.download.recipe
The URL for the download recipe has the URL hard coded in the download recipe instead of an Input variable.  Axure has made Axure PR 10 two distinct apps for x86 and arm with two different URLs - Intel - https://axure.cachefly.net/AxureRP-Setup.dmg ARM - https://axure.cachefly.net/AxureRP-Setup-arm64.dmg
This change moves the URL to the Input dictionary to be overridable in the Recipe Override.
=> Azure RP 10 has platform specific downloads

SoapUI/SoapUI.munki.recipe
There was an '#' to much in the shebang so the uninstall was in a loop.
=> Fixed uninstall Script

Ultimaker Cura/Ultimaker Cura.pkg.recipe
Also changed to use newer simplified AppPkgCreator processor. Have updated recipe MinimumVersion key to 1.0.0 accordingly. 
Recipe is now much simpler with only a single processor and uses glob for app name in case the name of .app file changes again in future. Have had to manually specify the bundle ID of "nl.ultimaker.cura" because the extracted CFBundleIdentifier bundle ID from the application contains invalid characters. 
Have tested this recipe in my own workflows and it now successfully produces the desired pkg again.
=> Updated Ultimaker Cura for change to app name

Microsoft Word 2019/Microsoft Word 2019.munki.recipe
The MunkiOptionalReceiptEditor processor was included beginning in AutoPkg 2.7, so recipes that use this processor should have `MinimumVersion` set accordingly.
=> Adjust minimum AutoPkg version for MunkiOptionalReceiptEditor

Perimeter 81/Perimeter 81.download.recipe, Perimeter 81/Perimeter 81.pkg.recipe
The P81 download and pkg recipes are failing for me with `Processor: URLTextSearcher: Error: No match found on URL: https://support.perimeter81.com/v1/docs/downloading-the-agent`
Looks like Perimeter 81 removed `https:` from the href links in https://support.perimeter81.com/v1/docs/downloading-the-agent.
PR includes updates to the regex search pattern to find the new links and this is tested as working for me.
=> update Perimeter 81 URLTextSearcher regex search pattern

Godot 3/Godot 3.pkg.recipe
changed the info path string to reflect the app name from the download recipe.
=> Update Godot 3.pkg.recipe

i1Profiler/i1Profiler.munki.recipe
The latest versions of i1 profiler were unable to launch in Ventura.
The added postinstall script fixes the permissions on two directories in Application Support to allow the app to launch.
=> Add in post install script to i1Profiler.munki.recipe

Amazon Corretto 8/Amazon Corretto 8.download.recipe
Recipe currently only downloads the Intel package for Amazon Corretto 8.  This pull request adds an ARCH input to allow for download of Intel or Apple Silicon packages.
=> add ARCH input to allow download of Intel or AS package

Canva/Canva.download.recipe
Slightly optimize the Canva download recipe by removing a processor relying on regex for an extant URL. Ran across this when running recipes in CI and the virtual runner wasn't properly finding a match. 
https://www.canva.com/download/mac/ already exposes https://www.canva.com/download/mac/universal/canva-desktop which redirects to the latest Canva version. No need to use `URLTextSearcher` to find a static URL. Instead move the user agent option to `URLDownloader` which ends up with the same result.
=> Remove URLTextSearcher from Canva download recipe

4K Video Downloader/4K Video Downloader.download.recipe
URLTextSearcher was returning no match. Without user-agent, site was returning a blank href on the search:
```<a id="videodownloader_macos_" href="" onclick="dataLayer.push({event: 'app_download', product: 'videodownloader'}); ga('send', 'event', 'Download page', 'Download', 'videodownloader__'); setAppDownloadedStatus('videodownloader'); return true;" class="btn btn--primary links-list__button"><span class="links-list__button-text">Download</span><img class="links-list__button-img" src="https://static.4kdownload.com/main/img/redesign/arrow-download.ad18a64e30f5.svg" alt="Download"></a>```
Adding a user-agent header caused the correct URL to appear, so included it in download recipe:
```<a id="videodownloader_macos_installer" href="https://dl.4kdownload.com/app/4kvideodownloader_4.29.0.dmg …
```
=> Update 4K Video Downloader.download.recipe

Microsoft Teams/Microsoft Teams.munki.recipe
The unattended install key with value `true` is duplicate, causing the post-install script of the pkg (which deletes to old app) to fail in cases where the old teams app is still running on the client. removed the duplicate key and changed the remaining to false.
=> Update Microsoft Teams.munki.recipe

Ultimaker Cura/Ultimaker Cura.download.recipe, Ultimaker Cura/Ultimaker Cura.munki.recipe
For situations when you want to import both architecture versions into Munki, you need the supported_architectures key. I added this in form of the SUPPORTED_ARCH variable which fills the supported_architectures pkginfo key. Also added description for usage.
=> add supported_architectures key for Munki

BrowserStackLocal/BrowserStackLocal App.download.recipe
The teamID for the Browserstack applications has recently changed. I noticed that @paul-cossey updated the download recipe for the binary, so this PR makes the same change for the app download recipe. I just tested and confirmed that this solves the `CodeSignatureVerifier: Error: Code signature verification failed` error.
=> Updated teamID for BrowserStack

MusicBrainz Picard/MusicBrainz Picard.pkg.recipe
I've submitted https://github.com/autopkg/tallfunnyjew-recipes/pull/30 to deprecate the broken download and pkg recipes for MusicBrainz Picard, and it would be nice to have a working pkg recipe to direct people to. This one is tested and working for me:
```
% autopkg run -vv 'MusicBrainz Picard/MusicBrainz Picard.pkg.recipe'
Processing MusicBrainz Picard/MusicBrainz Picard.pkg.recipe...
WARNING: MusicBrainz Picard/MusicBrainz Picard.pkg.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': '(MusicBrainz-Picard-([A-Za-z0-9]+(\\.[A-Za-z0-9]+)+)-macOS-10\\.14\\.dmg)',
'github_repo': 'metabrainz/picard'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl …
```
=> Create MusicBrainz Picard.pkg.recipe

FreeCAD/FreeCAD.download.recipe
I noticed that for some reason (maybe the app was not signed before), the download recipe does not include CodeSignatureVerification.
Would it be possible to add? For example the way I did on this pr.
Thanks in advance!
=> CodeSignatureVerification check added

Axure RP 10-Trial/Axure RP 10-Trial.download.recipe
NOTE:
- URL input has been removed
- ARCHITECTURE inout has been added. Set ARCHITECTURE to "-arm64" to download for Apple Silicon. Leave blank for Intel.
Fix for #365
=> Update Axure RP 10-Trial.download.recipe to pull down v10 only

Connect Fonts/Connect Fonts.download.recipe
Update the feed URL for v26 which came out recently. The version listed on the [download page](https://www.extensis.com/support/connect-fonts) hasn't been updated for the last two releases but the Mac link does download 26.0.0 now.
=> Update Connect Fonts.download.recipe

Perimeter 81/Perimeter 81.download.recipe
Perimeter 81 updated the pkg name and thus the download URL, PR updates the regex to reflect those changes.
The app contained in the pkg is still named the same, "Perimeter 81.app", so I'm only updating the URL regex to avoid additional confusion.
New URL: https://static.perimeter81.com/agents/mac/Harmony_SASE_11.0.10.2696.pkg
=> Update Perimeter 81 download recipe URLTextSearcher regex

Aspera Connect/Aspera Connect.munki.recipe
Aspera payloads now use lowercase letters for crypt, connect, and launcher.pkg files
=> Update Aspera Connect.munki.recipe

Lifesize/Lifesize.jss.recipe
[JSSImporter](https://github.com/jssimporter/JSSImporter) is no longer maintained. This pull request marks JSS type recipes as deprecated, and urges users to consider switching to equivalent [JamfUploader](https://github.com/grahampugh/jamf-upload/wiki/JamfUploader-AutoPkg-Processors) recipes.
Thanks for considering!
_This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0._
=> Deprecate JSS recipes

Hudl SportsCode 11/Hudl SportsCode 11.download.recipe
This PR deprecates the non-functional SportsCode 11 recipes and points users to the version 12 recipes in this repo.
=> Deprecate SportsCode 11 recipes

MakerBotPrint/MakerBotPrint.download.recipe
MakerBot Print is no longer in active development ([details](https://support.ultimaker.com/s/article/How-to-download-MakerBot-Print-for-Windows-and-Mac)). This PR deprecates the MakerBot Print recipes.
=> Deprecate MakerBot Print recipes

Godot 3/Godot 3.download.recipe, Godot 4/Godot 4.download.recipe
This PR adds code signature verification to the Gotot 3 and 4 recipes.
```
% autopkg run -vvq 'Godot 3/Godot 3.download.recipe' 'Godot 4/Godot 4.download.recipe'
Processing Godot 3/Godot 3.download.recipe...
WARNING: Godot 3/Godot 3.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': 'Godot_v3.\\d\\.\\d+-stable_mono_osx\\.universal\\.zip',
'github_repo': 'godotengine/godot'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting …
```
=> Add code signature verification to Godot recipes

FreeFileSync/FreeFileSync.download.recipe
The FreeFileSync recipes are redundant with the ones in the bnpl-recipes repo, and this is likely to create confusion and increase maintenance effort among AutoPkg users and admins. This PR deprecates the FreeFileSync recipes and points users to the ones in the bnpl-recipes repo.
=> Deprecate FreeFileSync recipes

FlashPrint 5/FlashPrint 5.download.recipe
This PR attempts to get the non-functional FlashPrint recipes back in working order. Currently, the macOS zip download is an image positioned after the Windows zip download, so the pattern has been adjusted to match the *second* instance of a zip link on the download page. This may need re-adjustment in the future if the relative positions of those images change, but it's the best we can do since there's no useful text to match. I left a comment in the URLTextSearcher process to explain this.
```
% autopkg run -vvq '~/Developer/repo-lasso/repos/autopkg/dataJAR-recipes/FlashPrint 5/FlashPrint 5.download.recipe'
Processing ~/Developer/repo-lasso/repos/autopkg/dataJAR-recipes/FlashPrint 5/FlashPrint 5.download.recipe...
WARNING: …
```
=> Fix FlashPrint recipes

ArrayCalc V10/ArrayCalc V10.download.recipe
This PR deprecates the non-functional ArrayCalc 10 recipes, and points users to the ArrayCalc 11 recipes elsewhere in this repo.
=> Deprecate ArrayCalc 10 recipes

Swiss-PdbViewer/Swiss-PdbViewer.download.recipe
This PR deprecates the non-functional Swiss-PdbViewer recipes, because the software is 32-bit and doesn't run on modern macOS versions ([details](https://spdbv.unil.ch)).
=> Deprecate Swiss-PdbViewer recipes

JDiskReport/JDiskReport.download.recipe
This PR fixes the download URL matching in the JDiskReport recipes.
```
% autopkg run -vvq 'JDiskReport/JDiskReport.download.recipe'
Processing JDiskReport/JDiskReport.download.recipe...
WARNING: JDiskReport/JDiskReport.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'Input': {'re_pattern': 'https://www.jgoodies.com/download/jdiskreport/jdiskreport-[\\d_]+-mac.zip',
'result_output_var_name': 'url',
'url': 'https://www.jgoodies.com/downloads/jdiskreport/'}}
URLTextSearcher: Found matching text (url): https://www.jgoodies.com/download/jdiskreport/jdiskreport-1_4_1-mac.zip
{'Output': {'url': 'https://www.jgoodies.com/download/jdiskreport/jdiskreport-1_4_1-mac.zip'}}
URLDownloader
{'Input': {'url': …
```
=> Fix JDiskReport recipes

Mplus Demo/MplusDemo.download.recipe
This PR fixes the MplusDemo recipes, because the software is currently available from a static URL which the URLTextSearcher pattern doesn't match.
```
% autopkg run -vvq 'Mplus Demo/MplusDemo.download.recipe'
Processing Mplus Demo/MplusDemo.download.recipe...
WARNING: Mplus Demo/MplusDemo.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'MplusDemo.pkg',
'url': 'https://www.statmodel.com/download/MplusDemo.pkg'}}
URLDownloader: Storing new Last-Modified header: Fri, 03 May 2024 14:07:34 GMT …
```
=> Fix MplusDemo recipes

UP Studio/UP Studio.download.recipe, UP Studio/UP Studio.munki.recipe, UP Studio/UP Studio.pkg.recipe
This PR fully reworks the Up Studio recipes to support the new app-in-dmg release format.
Note: code signature verification requirements have been enabled but commented out due to the fact that a certificate in the signing chain expired in 2022. This will likely be resolved whenever the next app release happens.
Verbose output from all recipe runs:
```
% autopkg run -vvq Up\ Studio.*.recipe
Processing UP Studio.download.recipe...
WARNING: UP Studio.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'Input': {'re_pattern': 'https://static\\.tiertime\\.com/downloads/mac/UpStudio_V\\d+\\.dmg',
'result_output_var_name': 'url',
'url': 'https://www.tiertime.com/software/'}}
URLTextSearcher: Found matching text (url): …
```
=> Fix Up Studio recipes

FreeFileSync/FreeFileSync.download.recipe
The bnpl-recipes versions are currently producing an error, so this PR reverts the change made by https://github.com/autopkg/dataJAR-recipes/pull/392.
=> Un-deprecate FreeFileSync recipes

Haiku/Haiku.download.recipe
EndOfCheckPhase is typically found immediately after URLDownloader. In the Haiku.download recipe they were reversed. This PR fixes that.
=> Put EndOfCheckPhase after download

pgAdmin4/pgAdmin4.download.recipe
The pgAdmin4 recipes in this repo are redundant with the ones offered in bnpl-recipes. This PR deprecates the pgAdmin4 recipes in this repo.
=> Deprecate pgAdmin4 recipes

RingCentral Classic/RingCentral Classic.download.recipe
The RingCentral Classic recipes in this repo are redandant with the ones in psaintemarie-recipes. This PR deprecates the RingCentral Classic recipes and points users to the psaintmarie-recipes repo instead.
=> Deprecate RingCentral Classic recipes

Pandoc/Pandoc.download.recipe, Pandoc/Pandoc.munki.recipe
The Pandoc recipes in this repo were created 2 weeks ago despite existing recipes being available from jleggat-recipes for many years. This PR deprecates the Pandoc recipes in this repo and points users to the jleggat-recipes alternatives.
=> Deprecate Pandoc recipes

BlockBlock/BlockBlock.download.recipe, BlockBlock/BlockBlock.munki.recipe
This PR changes the BlockBlock.pkg parent recipe to the download recipe in zentral-recipes, and deprecates the download recipe in this repo.
Verbose munki recipe run output:
```
% autopkg run -vvq BlockBlock.munki.recipe
Processing BlockBlock.munki.recipe...
WARNING: BlockBlock.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': '^.*\\.zip$',
'github_repo': 'objective-see/BlockBlock',
'include_prereleases': ''}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, …
```
=> Change parent of BlockBlock pkg recipe, deprecate download recipe

Inquisit 4 Lab/Inquisit 4 Lab.download.recipe, Inquisit 5 Lab/Inquisit 5 Lab.download.recipe, Inquisit 6 Lab/Inquisit 6 Lab.download.recipe, Inquisit Lab/Inquisit Lab.download.recipe, Inquisit Lab/Inquisit Lab.munki.recipe
This PR adds new recipes for Inquisit Lab that aren't tied to a specific major version of the software. A MAJOR_VERSION input variable has been added, set to the current major version (7) by default, which users can leverage to replicate the behavior of the current Inquisit Lab 6 recipes. This should enable seamless transition to future major versions, as long as other attributes of the app and package don't change significantly.
MAJOR_VERSION has been tested successfully with `6` and `7`. 5 and earlier are no longer available for download.
Verbose recipe run with default major version (7):
```
% autopkg run -vvq Inquisit\ Lab.*.recipe
Processing Inquisit Lab.download.recipe...
WARNING: Inquisit Lab.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. …
```
=> Create new non-version-specific Inquisit lab recipes

Perimeter 81/Perimeter 81.download.recipe, Perimeter 81/Perimeter 81.pkg.recipe
Expanding on the previously merged PR https://github.com/autopkg/dataJAR-recipes/pull/372 - perimeter 81 has further incorporated the "Harmony SASE" naming convention into their packages (though the application continues to be named "Perimeter 81.app").
PR addresses these changes.
=> Update Perimeter 81 recipes to use new pkg naming convention

OpenVPN Connect Client/OpenVPN Connect Client 3.download.recipe
Looks like they rebranded. Same org ID but "OPENVPN TECHNOLOGIES, INC." to "OpenVPN Inc."
=> updated code signature for OpenVPN

VKTablet/VKTablet.download.recipe
This PR deprecates the non-functional VKTablet download and munki recipes in this repo, which appear to have been replaced by the similarly-named VKTablet Driver recipes.
=> Deprecate VKTablet recipe

Snagit 2024/Snagit 2024.download.recipe
Snagit updated the dmg name in the download URL, using a lowercase `s` in `snagit.dmg` vs uppercase `S`.
Old: `https://download.techsmith.com/snagitmac/releases/2443/Snagit.dmg`
New: `https://download.techsmith.com/snagitmac/releases/2443/snagit.dmg`
This PR updates the regex to allow for both uppercase and lowercase `s` in the dmg name.
=> Update snagit regex to allow for lowercase dmg name

1Password CLI/OnePasswordCLIVersioner.py, Shared Processors/CFBundleVersionCombiner.py, VMware Fusion 10/VMwareFusion10URLProvider.py, VMware Fusion 8/VMwareFusion8URLProvider.py
An [upcoming version](https://github.com/munki/munki/wiki/Python-removal) of Munki will no longer include a Python framework. Therefore, the MunkiLooseVersion class will no longer be available, and should not be depended upon for AutoPkg processors or recipes.
This PR changes the processor references to MunkiLooseVersion to APLooseVersion, which should be an easy drop-in replacement.
Other changes will be needed to recipes in this repo to move away from importing from munkilib, but those changes are outside of the scope of this PR.
Thanks for considering!
=> Switch from MunkiLooseVersion to APLooseVersion for version comparisons

SketchUp 2025 EN/SketchUp 2025 EN.download.recipe, SketchUp 2025 EN/SketchUp 2025 EN.munki.recipe
I see that the `URLDownloader` is using cookies.txt for something, but on my setup that file does not appear to actually be used. This is causing AutoPkg to error out, since PathDeleter fails to delete it.
I removed `%RECIPE_CACHE_DIR%/cookies.txt` from the PathDeleter processor step
=> Sketchup 2025 EN - Remove cookies.txt from PathDeleter

ArrayCalc V12/ArrayCalc V12.download.recipe, Coot/Coot.download.recipe, Disk Inventory X/Disk Inventory X.download.recipe, Finale 26-Trial/Finale26-Trial.download.recipe, Finale 27/Finale27.download.recipe, R1 V3/R1 V3.download.recipe, SoapUI/SoapUI.download.recipe, VPT8/VPT8.munki.recipe
It's important to use HTTPS for downloading software whenever possible in order to avoid the possibility of person-in-the-middle attacks (like the one that affected the Sparkle update framework [back in 2016](https://vulnsec.com/2016/osx-apps-vulnerabilities/)).
For this pull request, I detected and changed to HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure exit codes of recipe run remains the same before/after the change.
Thanks for considering!
_This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0._
=> Update all available URLs from HTTP to HTTPS
